name: PR Tests - Housing Price Prediction API

on:
  pull_request:
    branches: [main, develop]
    types: [opened, synchronize, reopened]

env:
  PYTHON_VERSION: "3.11"

jobs:
  pr-tests:
    name: Quick Tests for PR
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: ${{ env.PYTHON_VERSION }}
          cache: "pip"

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt
          pip install black flake8 pytest

      - name: Code formatting check (Black)
        run: |
          black --check --diff src/ tests/

      - name: Linting (Flake8)
        run: |
          flake8 src/ tests/ --max-line-length=88 --extend-ignore=E203,W503

      - name: Train model for tests
        run: |
          cd src
          python train_model.py
          cd ..

      - name: Run unit tests
        run: |
          python -m pytest tests/ -v --tb=short

      - name: Test API endpoints
        run: |
          python -c "
          import sys
          import os
          sys.path.insert(0, 'src')

          # Import et test basique
          try:
              from main import app
              print('Import de l\'API réussi')
          except Exception as e:
              print(f'❌ Erreur import API: {e}')
              sys.exit(1)
          "

      - name: PR Summary Comment
        if: always()
        run: |
          echo "## Résultats des tests PR" >> $GITHUB_STEP_SUMMARY
          echo "" >> $GITHUB_STEP_SUMMARY
          echo "### Tests réalisés:" >> $GITHUB_STEP_SUMMARY
          echo "- Formatage du code (Black)" >> $GITHUB_STEP_SUMMARY
          echo "- Qualité du code (Flake8)" >> $GITHUB_STEP_SUMMARY
          echo "- Entraînement du modèle ML" >> $GITHUB_STEP_SUMMARY
          echo "- Tests unitaires" >> $GITHUB_STEP_SUMMARY
          echo "- Import de l'API" >> $GITHUB_STEP_SUMMARY
          echo "" >> $GITHUB_STEP_SUMMARY
          echo "**Cette PR est prête pour la review!**" >> $GITHUB_STEP_SUMMARY
